name: Deploy Laravel Project on push
on:
  push:
    branches:
      - server
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: Check if .env exists
        id: check_env_file
        run: |
          if [ -f .env ]; then
            echo "::set-output name=env_exists::true"
          else
            echo "::set-output name=env_exists::false"
          fi
      - name: Copy .env
        if: steps.check_env_file.outputs.env_exists == 'false'
        run: cp .env.example .env
      - name: Fill .env with default values
        if: steps.check_env_file.outputs.env_exists == 'false'
        run: |
          sed -i "s#DB_DATABASE=laravel#DB_DATABASE=${{ secrets.DB_DATABASE }}#" .env
          sed -i "s#DB_USERNAME=root#DB_USERNAME=${{ secrets.DB_USERNAME }}#" .env
          sed -i "s#DB_PASSWORD=#DB_PASSWORD=${{ secrets.DB_PASSWORD }}#" .env
          sed -i "s#APP_URL=http://localhost#APP_URL=${{ secrets.APP_URL }}#" .env
      - name: Install Dependencies
        run: composer install --ignore-platform-reqs
      - name: Generate key
        run: php artisan key:generate
      - name: Generate storage link
        run: php artisan storage:link
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
