name: Deploy Laravel Project on push
on:
  push:
    branches:
      - server
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: Check if .env exists
        id: check_env_file
        run: |
          if [ -f .env ]; then
            echo "::set-output name=env_exists::true"
          else
            echo "::set-output name=env_exists::false"
          fi
      - name: Copy .env
        if: steps.check_env_file.outputs.env_exists == 'false'
        run: cp .env.example .env
      - name: Install Dependencies
        run: composer install --ignore-platform-reqs
      - name: Generate key
        run: php artisan key:generate
      - name: Generate storage link
        run: php artisan storage:link
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
